version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/frontend"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/src/backend"
    schedule:
      interval: "daily"
